# Generated by Django 4.2.5 on 2023-10-29 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro_CSTF',
            fields=[
                ('docente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.docente')),
                ('resolucion_asignacion', models.IntegerField(unique=True)),
                ('fecha_alta', models.DateField()),
            ],
            bases=('persona.docente',),
        ),
        migrations.CreateModel(
            name='Miembro_TE',
            fields=[
                ('docente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.docente')),
                ('rol', models.CharField(max_length=100)),
                ('fecha_alta', models.DateField()),
            ],
            bases=('persona.docente',),
        ),
        migrations.CreateModel(
            name='TribunalEvaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disposicion', models.DateField()),
                ('numero_disposicion', models.IntegerField(unique=True)),
                ('archivo_disposicion', models.FileField(upload_to='')),
                ('miembros', models.ManyToManyField(to='comision.miembro_te')),
            ],
        ),
    ]
