# Generated by Django 4.2.5 on 2023-10-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunalevaluador',
            name='numero_disposicion',
            field=models.IntegerField(),
        ),
    ]
