# Generated by Django 4.2.5 on 2023-10-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_TF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta_alumno', models.DateField()),
                ('fecha_alta_director', models.DateField()),
                ('fecha_alta_co_director', models.DateField()),
                ('fecha_alta_asesor', models.DateField(blank=True, null=True)),
                ('titulo_ptf', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_presentacion', models.DateField()),
                ('archivos_adjuntos_ptf', models.FileField(upload_to='')),
                ('certificado_analitico', models.FileField(upload_to='')),
                ('nota_aceptacion_director', models.FileField(upload_to='')),
                ('asesor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor_proyecto', to='persona.docente')),
                ('co_director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codirector_proyecto', to='persona.docente')),
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_proyecto', to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_TF_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_tf', to='persona.alumno')),
                ('proyecto_tf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='proyectotf.proyecto_tf')),
            ],
        ),
        migrations.CreateModel(
            name='Informe_TF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=5, unique=True)),
                ('archivo_itf', models.FileField(upload_to='archivos_itf/')),
                ('proyecto_tf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_tf', to='proyectotf.proyecto_tf')),
            ],
        ),
    ]
