# Generated by Django 4.2.5 on 2023-11-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionptf',
            name='informe',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='evaluacionptf',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
