# Generated by Django 4.2.5 on 2023-10-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionitf',
            name='observaciones',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionptf',
            name='observaciones',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
